### ISSUE TITLE
Add aria2 support

### ISSUE THREAD

**Issue by runo280** [commandlineget/commandlineget#1]

**Comment by commandlineget** [comment]
I don't really use aria much myself except special cases, but why not.

Pushed preliminary aria2c support in:  [d6927c4431081a2c54ea78470444185f11928bc7](https://github.com/commandlineget/commandlineget/commit/d6927c4431081a2c54ea78470444185f11928bc7)

**Comment by commandlineget** [comment]
closed: feature added
